In [1]:
import numpy as np

In [2]:
arr = np.array([12, 23, 45, 56, 32])

In [3]:
arr

array([12, 23, 45, 56, 32])

In [4]:
print(arr)

[12 23 45 56 32]


In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.dtype

dtype('int32')

In [7]:
arr = np.array([12, 23, 45, 56, 32, 66.22])

In [8]:
arr.dtype

dtype('float64')

In [9]:
arr

array([12.  , 23.  , 45.  , 56.  , 32.  , 66.22])

In [10]:
arr = np.array([12, 23, 45, 56, 32, 66.22, 'Pune'])

In [11]:
arr

array(['12', '23', '45', '56', '32', '66.22', 'Pune'], dtype='<U32')

In [12]:
arr.dtype

dtype('<U32')

In [13]:
%%timeit
arr = np.array([12, 23, 45, 56, 32, 66.22, 'Pune'])

2.32 μs ± 112 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [15]:
arr[3]

'56'

In [16]:
arr.shape

(7,)

In [17]:
arr = np.array([12, 23, 45, 56, 32])

In [18]:
arr * 2

array([ 24,  46,  90, 112,  64])

In [19]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
np.arange(2, 20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [22]:
np.arange(2, 20, 2.5)

array([ 2. ,  4.5,  7. ,  9.5, 12. , 14.5, 17. , 19.5])

In [23]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [30]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
arr1.shape

(4, 3)

In [32]:
arr1.ndim

2

In [33]:
arr1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
arr1.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
arr1.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [42]:
arr1.reshape(4,-1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [47]:
arr1.reshape(3, 2, 2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [48]:
arr1.reshape(4,3,-1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [49]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
arr1[0:3,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [52]:
arr1[0:4, 0: 3]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [53]:
arr

array([12, 23, 45, 56, 32])

In [54]:
arr.mean()

33.6

In [55]:
arr.min()

12

In [58]:
arr = np.array([1,3,2,4,2,3,4,9])

In [59]:
np.unique(arr)

array([1, 2, 3, 4, 9])

In [60]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
np.linalg.det(arr1)

0.0

In [63]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
arr1 @ arr2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [67]:
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])