#### Q1. Create a package named ‘cricket’ which will contain modules named batsman and bowler. Create following functions in respective modules. Import the package and call all these functions in your program batsman: findaverage(runs,matches), strikerate(runs,balls) bowler: findavg(runs,wickets), economyrate(overs, runs)

In [ ]:
from cricket import batsman as bt
from cricket import bowler as bw
print("BATSMAN")
print("If Runs = 4042 , Outs = 47 Then Batsman's Average = ",bt.findaverage(4042,47))
print("If Runs = 264 , Balls = 173 Then Batsman's Strikerate = ",bt.strikerate(264,173))
print("BOWLER")
print("If Runs = 3857 , Wickets = 138 Then Bowler's Average = ",bw.findavg(3857,138))
print("If Overs = 4 , Runs = 36 Then Bowler's Economy Rate = ",bw.economyrate(4,36))

#### Q.2 Write a Python function to find whether the number if prime or not. def isPrime(num)

In [7]:
num = int(input("Enter the num:- "))
def isPrime(num):
    flag = False
    if num > 1:
        for i in range(2, num):
            if num % i == 0:
                flag = True

    if flag == True:
        print(num, "is not a prime number")
    else:
        print(num, "is prime number")

isPrime(num)

10 is not a prime number


#### Q3.Write a function is_palindrome(string) that takes a string as input and returns True if the string reads the same backward as forward (e.g., "racecar" is a palindrome).

In [3]:
string = input()
print("Enter String:- ", string)

def is_palindrome(string):
    rev = string[::-1]
    print("Reversed String:- " , rev)
    if string == rev:
        print(string , "is a Palindrome.")
    else:
        print(string , "is not a Palindrome")

is_palindrome(string)

Enter String:-  Alpit
Reversed String:-  tiplA
Alpit is not a Palindrome


#### Q4. Write a function reverse_list(data) that takes a list as input and returns a new list with the elements in reverse order (e.g., reverse_list([1, 2, 3]) returns [3, 2, 1]).

In [3]:
l1 = []
for i in range(10):
    n = int(input())
    l1.append(n)

def reverse_list(data):
    result = data[::-1]
    return result

print(reverse_list(l1))

[1000, 900, 800, 700, 600, 500, 400, 300, 200, 100]


#### Q5.Write a function write_file(filename, content) that takes a filename and content as input and writes the content to the specified file.

In [16]:
# with open('Intro.txt', 'w') as w:
    # w.write("I am Alpit. I Studing in Ajeenkya DY Patil School of Engineering, and I am working as a intern at MITU Skillologies.")

filename = input()
# content = '''"Python is Easy language"''' "I am Alpit. I Studing in Ajeenkya DY Patil School of Engineering, and I am working as a intern at MITU Skillologies."
content = input()

def write_file(filename, content):
    with open(filename , 'w') as w:
        w.write(content)

write_file(filename, content)

#### Q6. Write a function copy_file(source_filename, destination_filename) that takes the source and destination filenames as input and copies the content of the source file to the destination file. Handle cases where the source file doesn't exist.

In [4]:


def copy_file(source_filename, destination_filename):
    try:
        with open(source_filename, 'r') as d1:
            with open(destination_filename, 'w') as d2:
                for n in d1:
                    d2.write(n)
    except FileNotFoundError:
        print("The Source file doesn't exist.")
    except Exception as e:
        print("Your Error id:- ", e )
    else:
        print("Your file is copied successfully")

source_filename = input()
destination_filename = input()
copy_file(source_filename, destination_filename)

The Source file doesn't exist.


#### Q7. Implement a function to calculate the dot product of two NumPy arrays.


In [19]:
import numpy as np 

arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

def dot_pr(arr1,arr2):
    dp = arr1 * arr2
    print(dp)

dot_pr(arr1,arr2)


[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


#### Q8. Implement a GUI with a radio button selection for choosing a favorite color (e.g., red, green, blue). Change the background color of the window based on the selected radio button.

In [4]:
from tkinter import Tk, Radiobutton, StringVar 
import tkinter as tk

ag = Tk()
ag.title("Vishay Kholl")
ag.geometry("500x500")
l1 = tk.Label(ag, text = "Select Favorite Color", font = ("Aerial Bold", 15)).pack()
def update_color(color):
    ag.config(bg=color)
colors =  ['Black', 'Blue','Grey','Red','Orange','Brown','Pink','Yellow']
selected_color = StringVar()
for color in colors:
    radio_button = Radiobutton(ag, text = color, variable = selected_color, value = color, command = lambda c=color : update_color(c))
    radio_button.pack() 

update_color(color)
ag.mainloop()

#### Q9. Design a currency converter GUI. Allow users to enter an amount and select the currencies they want to convert between (e.g., USD, EUR). Display the converted amount in the selected currency.

In [5]:
from tkinter import  Tk, messagebox, BooleanVar
from tkinter.ttk import * 
import tkinter as tk

coc = Tk()
coc.title("Currency Convertor")
coc.geometry("610x610")
l1 = tk.Label(coc, text = "Corrency Convertor" , font = ("Times New Roman", 15)).pack()

a = tk.IntVar()
e = tk.Entry(coc, textvariable = a).place(x = 240, y = 70)
combo = Combobox(coc)
combo['values'] = ['Select the Currencies','USD', 'EUR', 'POUND', 'KWD', 'BHD', 'OMR']
combo.current(0)
combo.place(x = 230, y = 40)

def usd():
    a1 = a.get()
    convert = a1 * 83
    messagebox.showinfo("Value Calculated", "You have Balance of %i INR"%convert)

coc.mainloop()




In [4]:
import tkinter as tk
from tkinter import messagebox



top = tk.Tk()
top.title("Currency Calculator")
top.geometry("700x700")
top.configure(bg = "cornsilk")
inr = tk.IntVar()
#i  = tk.PhotoImage(file = "")
#bg = tk.Label(top,image = i)
#bg.place(relwidth=1, relheight=1)

def usd():
    a = inr.get()
    u = a/83
    messagebox.showinfo("converter","USD = %i" %u )
def eur():
    a = inr.get()
    e = a/89
    messagebox.showinfo("converter","EUR = %i" %e )
def pound():
    a = inr.get()
    p = a/105
    messagebox.showinfo("converter","POUND = %i" %p )
def dinar():
    a = inr.get()
    d = a/272
    messagebox.showinfo("converter","DINAR = %i" %d )
l = tk.Label(top,text = "Enter your Amount in INR ",font = "khand", bg = "snow3").place(x = 250, y = 150)
e = tk.Entry(top, textvariable = inr,width = 30).place(x = 270, y = 190)
b1 = tk.Button(top,text = "USD",width = 20,bg = "NavajoWhite3",command = usd).place(x = 290, y = 220)
b2 = tk.Button(top,text = "EUR",width = 20,bg = "NavajoWhite3",command = eur).place(x = 290, y = 250)
b3 = tk.Button(top,text = "POUND",width = 20,bg = "NavajoWhite3",command = pound).place(x = 290, y = 280)
b4 = tk.Button(top,text = "DINAR",width = 20,bg = "NavajoWhite3",command = dinar).place(x = 290, y = 310)
top.mainloop()